# Useful links
github_username: "<github_username>"
facebook_username: "<facebook_username>"
twitter_username: "<twitter_username>"
linkedin_id: "<linkedin_id>"

# Theme
# theme: jekyll-theme-potato-hacker                 # Uncomment this
# remote_theme: luxedo/jekyll-theme-potato-hacker   # Or this
theme_repository: "https://github.com/luxedo/jekyll-theme-potato-hacker"
theme_base: "dark"       # Theme palette (light | dark)
theme_switch: on         # Show color switch (on | off)

# Extra settings
blog: on                 # Show blog tag and post list (on | off)
avatar: on               # Show avatar (on | off)
avatar_image: "assets/img/cover-1.png"
avatar_description: "Mochimomo"
highlighter_theme: monokai  # Theme of the syntax_highlighter [base16 |
                            # colorful | github | gruvbox | molokai |
                            # monokai | pastie | thankful_eyes | tulip ]
toolbar_priority:        # Order of the items in the toolbar (except for blog and home)
  - dropdown2
  - About
  - dropdown1

# Collections
collections:
  dropdown:
    output: true
  items:
    output: true
